options:
  dcf_path: "/home/belev/autofork_ws/install/motor_control/share/motor_control/config/robot_control"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000  # 10 ms sync period

traction_motor:
  node_id: 2
  dcf: "Kinco_FD_20250417_V1.2.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10
  revision_number: 0
  sdo:
    - {index: 0x6040, sub_index: 0, value: 128}  # Reset fault (Controlword bit 7)
    - {index: 0x1017, sub_index: 0, value: 1000} # Enable heartbeats every 1000 ms (16-bit)
    - {index: 0x6060, sub_index: 0, value: 3}    # Profile Velocity Mode
    - {index: 0x6040, sub_index: 0, value: 6}    # Shutdown (transition to Ready to Switch On)
    - {index: 0x6040, sub_index: 0, value: 7}    # Switch On
    - {index: 0x6040, sub_index: 0, value: 15}   # Enable Operation
  tpdo:
    1:
      enabled: true
      cob_id: "auto" 
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0}  # Statusword
        - {index: 0x6061, sub_index: 0}  # Mode of Operation Display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}  # Actual Position
        - {index: 0x606C, sub_index: 0}  # Actual Velocity
    3:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0}  # Forklift Target Reached Bit
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0}  # Controlword
        - {index: 0x6060, sub_index: 0}  # Mode of Operation
    3:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x60FF, sub_index: 0}  # Target Velocity