options:
  dcf_path: "/home/belev/autofork_ws/install/motor_control/share/motor_control/config/robot_control"
  #dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000  # 10 ms sync period
  boot_time: 500  # Timeout for booting mandatory slaves in ms

traction_motor:
  node_id: 2
  dcf: "Kinco_FD_20250417_V1.2.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10
  boot: true  # Specifies whether the slave will be configured and booted by the master
  enable_lazy_load: true
  polling: false
  
  scale_pos_to_dev: 2607.5946
  scale_pos_from_dev: 0.0003835
  
  scale_vel_to_dev: 428390.541428 # considering gear ratio to multiply (1:23) (and experimental 1.4 ratio to divide)
  scale_vel_from_dev: 0.000002334 # considering gear ratio to multiply (1:23) (and experimental 1.4 ratio to divide)
  
  #scale_vel_to_dev: 26075.946
  #scale_vel_from_dev: 0.00003835
  velocity_mode: 1  # Set to Profile Velocity Mode
  sdo:
    - {index: 0x6040, sub_index: 0, value: 128}  # Reset fault
    - {index: 0x1017, sub_index: 0, value: 1000} # Enable heartbeats every 1000 ms
    - {index: 0x6060, sub_index: 0, value: 3}    # Profile Velocity Mode
    - {index: 0x6040, sub_index: 0, value: 6}    # Shutdown
    - {index: 0x6040, sub_index: 0, value: 7}    # Switch On
    - {index: 0x6040, sub_index: 0, value: 15}   # Enable Operation
    - {index: 0x6081, sub_index: 0, value: 10}   # Set velocity
    - {index: 0x6083, sub_index: 0, value: 200}  # Set acceleration
    - {index: 0x6084, sub_index: 0, value: 500}  # Set deceleration
    - {index: 0x6085, sub_index: 0, value: 50}   # Set quickstop deceleration
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0}  # Statusword
        - {index: 0x6061, sub_index: 0}  # Mode of Operation Display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}  # Actual Position
        - {index: 0x606C, sub_index: 0}  # Actual Velocity
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0}  # Controlword
        - {index: 0x6060, sub_index: 0}  # Mode of Operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x60FF, sub_index: 0}  # Target Velocity