options:
  dcf_path: "/home/belev/autofork_ws/install/motor_control/share/motor_control/config/robot_control"
  #dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 1
  driver: "ros2_canopen::MasterDriver"
  package: "canopen_master_driver"
  sync_period: 10000  # 10 ms sync period
  boot_time: 500  # Timeout for booting mandatory slaves in ms

traction_motor:
  node_id: 2
  dcf: "Kinco_FD_20250417_V1.2.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10
  boot: true  # Specifies whether the slave will be configured and booted by the master
  enable_lazy_load: true
  polling: false
  
  scale_pos_to_dev: 2607.5946
  scale_pos_from_dev: 0.0003835
  
  scale_vel_to_dev: 428390.541428 # considering gear ratio to multiply (1:23) (and experimental 1.4 ratio to divide)
  scale_vel_from_dev: 0.000002334 # considering gear ratio to multiply (1:23) (and experimental 1.4 ratio to divide)
  
  #scale_vel_to_dev: 26075.946
  #scale_vel_from_dev: 0.00003835
  velocity_mode: 1  # Set to Profile Velocity Mode
  sdo:
    - {index: 0x6040, sub_index: 0, value: 128}  # Reset fault
    - {index: 0x1017, sub_index: 0, value: 1000} # Enable heartbeats every 1000 ms
    - {index: 0x6060, sub_index: 0, value: 3}    # Profile Velocity Mode
    - {index: 0x6040, sub_index: 0, value: 6}    # Shutdown
    - {index: 0x6040, sub_index: 0, value: 7}    # Switch On
    - {index: 0x6040, sub_index: 0, value: 15}   # Enable Operation
    - {index: 0x6081, sub_index: 0, value: 10}   # Set velocity
    - {index: 0x6083, sub_index: 0, value: 1500}  # Set acceleration (already: 200)
    - {index: 0x6084, sub_index: 0, value: 2500}  # Set deceleration (already: 500)
    - {index: 0x6085, sub_index: 0, value: 250}   # Set quickstop deceleration (already: 50)
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0}  # Statusword
        - {index: 0x6061, sub_index: 0}  # Mode of Operation Display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}  # Actual Position
        - {index: 0x606C, sub_index: 0}  # Actual Velocity
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0}  # Controlword
        - {index: 0x6060, sub_index: 0}  # Mode of Operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x60FF, sub_index: 0}  # Target Velocity

steering_motor:
  node_id: 3
  dcf: "Kinco_FD_20250417_V1.2.eds"
  driver: "ros2_canopen::Cia402Driver"
  package: "canopen_402_driver"
  period: 10
  boot: true
  enable_lazy_load: true
  polling: false

  # fork positioning
  #scale_pos_to_dev: 13986013.9860 #(increments per meter) | old: 2607.5946
  #scale_pos_from_dev: 0.0000000715 #(meters per increment) | old: 0.0003835

  # steering wheel positioning
  scale_pos_to_dev: 3271863.6623 #292845.0953 # ≈ 1,840,000 / (2π) | old: 2607.5946
  scale_pos_from_dev: 0.000000306 #0.0000034148 # ≈ (2π) / 1,840,000 | old: 0.0003835

  scale_vel_to_dev: 26075.946
  scale_vel_from_dev: 0.00003835
  position_mode: 1
  sdo:
    - {index: 0x6040, sub_index: 0, value: 128}   # Reset fault
    - {index: 0x1017, sub_index: 0, value: 1000}  # Enable heartbeats every 1000 ms
    - {index: 0x6060, sub_index: 0, value: 1}     # Profile Position Mode
    - {index: 0x6081, sub_index: 0, value: 35835301} # Profile velocity (~ 2000 RPM) (wheel's motor)
    #- {index: 0x6081, sub_index: 0, value: 2730650} # Profile velocity (~ 1000 RPM) (forks' motor)
    - {index: 0x6098, sub_index: 0, value: 1}     # Homing method
    - {index: 0x6083, sub_index: 0, value: 60000}   # Set acceleration (already: 200)
    - {index: 0x6084, sub_index: 0, value: 90000}   # Set deceleration (already: 500)
    #- {index: 0x6083, sub_index: 0, value: 200}   # Set acceleration (forks)
    #- {index: 0x6084, sub_index: 0, value: 500}   # Set deceleration (forks)
    - {index: 0x6085, sub_index: 0, value: 250}    # Set quickstop deceleration (already: 50)
    - {index: 0x6040, sub_index: 0, value: 6}     # Shutdown
    - {index: 0x6040, sub_index: 0, value: 7}     # Switch On
    - {index: 0x6040, sub_index: 0, value: 15}    # Enable Operation

  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6041, sub_index: 0}  # Statusword
        - {index: 0x6061, sub_index: 0}  # Mode of Operation Display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - {index: 0x6064, sub_index: 0}  # Actual Position
        - {index: 0x606C, sub_index: 0}  # Actual Velocity
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x6040, sub_index: 0}  # Controlword
        - {index: 0x6060, sub_index: 0}  # Mode of Operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - {index: 0x607A, sub_index: 0}  # Target Position